INSERT INTO extLinks VALUES('Angel Hideaway',NULL);
INSERT INTO extLinks VALUES('Angel Hidden Hideaway',NULL);
INSERT INTO extLinks VALUES('Angel Forsaken Hideaway',NULL);
INSERT INTO extLinks VALUES('Angel Forlorn Hideaway',NULL);
INSERT INTO extLinks VALUES('Angel Burrow',NULL);
INSERT INTO extLinks VALUES('Angel Refuge',NULL);
INSERT INTO extLinks VALUES('Angel Den',NULL);
INSERT INTO extLinks VALUES('Angel Hidden Den',NULL);
INSERT INTO extLinks VALUES('Angel Forsaken Den',NULL);
INSERT INTO extLinks VALUES('Angel Forlorn Den',NULL);
INSERT INTO extLinks VALUES('Angel Yard',NULL);
INSERT INTO extLinks VALUES('Angel Rally Point',NULL);
INSERT INTO extLinks VALUES('Angel Hidden Rally Point',NULL);
INSERT INTO extLinks VALUES('Angel Forsaken Rally Point',NULL);
INSERT INTO extLinks VALUES('Angel Forlorn Rally Point',NULL);
INSERT INTO extLinks VALUES('Angel Port',NULL);
INSERT INTO extLinks VALUES('Angel Hub',NULL);
INSERT INTO extLinks VALUES('Angel Hidden Hub',NULL);
INSERT INTO extLinks VALUES('Angel Forsaken Hub',NULL);
INSERT INTO extLinks VALUES('Angel Forlorn Hub',NULL);
INSERT INTO extLinks VALUES('Angel Haven',NULL);
INSERT INTO extLinks VALUES('Angel Sanctum',NULL);
INSERT INTO extLinks VALUES('Blood Hideaway',NULL);
INSERT INTO extLinks VALUES('Blood Hidden Hideaway',NULL);
INSERT INTO extLinks VALUES('Blood Forsaken Hideaway',NULL);
INSERT INTO extLinks VALUES('Blood Forlorn Hideaway',NULL);
INSERT INTO extLinks VALUES('Blood Burrow',NULL);
INSERT INTO extLinks VALUES('Blood Refuge',NULL);
INSERT INTO extLinks VALUES('Blood Den',NULL);
INSERT INTO extLinks VALUES('Blood Hidden Den',NULL);
INSERT INTO extLinks VALUES('Blood Forsaken Den',NULL);
INSERT INTO extLinks VALUES('Blood Forlorn Den',NULL);
INSERT INTO extLinks VALUES('Blood Yard',NULL);
INSERT INTO extLinks VALUES('Blood Rally Point',NULL);
INSERT INTO extLinks VALUES('Blood Hidden Rally Point',NULL);
INSERT INTO extLinks VALUES('Blood Forsaken Rally Point',NULL);
INSERT INTO extLinks VALUES('Blood Forlorn Rally Point',NULL);
INSERT INTO extLinks VALUES('Blood Port',NULL);
INSERT INTO extLinks VALUES('Blood Hub',NULL);
INSERT INTO extLinks VALUES('Blood Hidden Hub',NULL);
INSERT INTO extLinks VALUES('Blood Forsaken Hub',NULL);
INSERT INTO extLinks VALUES('Blood Forlorn Hub',NULL);
INSERT INTO extLinks VALUES('Blood Haven',NULL);
INSERT INTO extLinks VALUES('Blood Sanctum',NULL);
INSERT INTO extLinks VALUES('Guristas Hideaway',NULL);
INSERT INTO extLinks VALUES('Guristas Hidden Hideaway',NULL);
INSERT INTO extLinks VALUES('Guristas Forsaken Hideaway',NULL);
INSERT INTO extLinks VALUES('Guristas Forlorn Hideaway',NULL);
INSERT INTO extLinks VALUES('Guristas Burrow',NULL);
INSERT INTO extLinks VALUES('Guristas Refuge',NULL);
INSERT INTO extLinks VALUES('Guristas Den',NULL);
INSERT INTO extLinks VALUES('Guristas Hidden Den',NULL);
INSERT INTO extLinks VALUES('Guristas Forsaken Den',NULL);
INSERT INTO extLinks VALUES('Guristas Forlorn Den',NULL);
INSERT INTO extLinks VALUES('Guristas Yard',NULL);
INSERT INTO extLinks VALUES('Guristas Rally Point',NULL);
INSERT INTO extLinks VALUES('Guristas Hidden Rally Point',NULL);
INSERT INTO extLinks VALUES('Guristas Forsaken Rally Point',NULL);
INSERT INTO extLinks VALUES('Guristas Forlorn Rally Point',NULL);
INSERT INTO extLinks VALUES('Guristas Port',NULL);
INSERT INTO extLinks VALUES('Guristas Hub',NULL);
INSERT INTO extLinks VALUES('Guristas Hidden Hub',NULL);
INSERT INTO extLinks VALUES('Guristas Forsaken Hub',NULL);
INSERT INTO extLinks VALUES('Guristas Forlorn Hub',NULL);
INSERT INTO extLinks VALUES('Guristas Haven',NULL);
INSERT INTO extLinks VALUES('Guristas Sanctum',NULL);
INSERT INTO extLinks VALUES('Sansha Hideaway',NULL);
INSERT INTO extLinks VALUES('Sansha Hidden Hideaway',NULL);
INSERT INTO extLinks VALUES('Sansha Forsaken Hideaway',NULL);
INSERT INTO extLinks VALUES('Sansha Forlorn Hideaway',NULL);
INSERT INTO extLinks VALUES('Sansha Burrow',NULL);
INSERT INTO extLinks VALUES('Sansha Refuge',NULL);
INSERT INTO extLinks VALUES('Sansha Den',NULL);
INSERT INTO extLinks VALUES('Sansha Hidden Den',NULL);
INSERT INTO extLinks VALUES('Sansha Forsaken Den',NULL);
INSERT INTO extLinks VALUES('Sansha Forlorn Den',NULL);
INSERT INTO extLinks VALUES('Sansha Yard',NULL);
INSERT INTO extLinks VALUES('Sansha Rally Point',NULL);
INSERT INTO extLinks VALUES('Sansha Hidden Rally Point',NULL);
INSERT INTO extLinks VALUES('Sansha Forsaken Rally Point',NULL);
INSERT INTO extLinks VALUES('Sansha Forlorn Rally Point',NULL);
INSERT INTO extLinks VALUES('Sansha Port',NULL);
INSERT INTO extLinks VALUES('Sansha Hub',NULL);
INSERT INTO extLinks VALUES('Sansha Hidden Hub',NULL);
INSERT INTO extLinks VALUES('Sansha Forsaken Hub',NULL);
INSERT INTO extLinks VALUES('Sansha Forlorn Hub',NULL);
INSERT INTO extLinks VALUES('Sansha Haven',NULL);
INSERT INTO extLinks VALUES('Sansha Sanctum',NULL);
INSERT INTO extLinks VALUES('Serpentis Hideaway',NULL);
INSERT INTO extLinks VALUES('Serpentis Hidden Hideaway',NULL);
INSERT INTO extLinks VALUES('Serpentis Forsaken Hideaway',NULL);
INSERT INTO extLinks VALUES('Serpentis Forlorn Hideaway',NULL);
INSERT INTO extLinks VALUES('Serpentis Burrow',NULL);
INSERT INTO extLinks VALUES('Serpentis Refuge',NULL);
INSERT INTO extLinks VALUES('Serpentis Den',NULL);
INSERT INTO extLinks VALUES('Serpentis Hidden Den',NULL);
INSERT INTO extLinks VALUES('Serpentis Forsaken Den',NULL);
INSERT INTO extLinks VALUES('Serpentis Forlorn Den',NULL);
INSERT INTO extLinks VALUES('Serpentis Yard',NULL);
INSERT INTO extLinks VALUES('Serpentis Rally Point',NULL);
INSERT INTO extLinks VALUES('Serpentis Hidden Rally Point',NULL);
INSERT INTO extLinks VALUES('Serpentis Forsaken Rally Point',NULL);
INSERT INTO extLinks VALUES('Serpentis Forlorn Rally Point',NULL);
INSERT INTO extLinks VALUES('Serpentis Port',NULL);
INSERT INTO extLinks VALUES('Serpentis Hub',NULL);
INSERT INTO extLinks VALUES('Serpentis Hidden Hub',NULL);
INSERT INTO extLinks VALUES('Serpentis Forsaken Hub',NULL);
INSERT INTO extLinks VALUES('Serpentis Forlorn Hub',NULL);
INSERT INTO extLinks VALUES('Serpentis Haven',NULL);
INSERT INTO extLinks VALUES('Serpentis Sanctum',NULL);
INSERT INTO extLinks VALUES('Drone Cluster',NULL);
INSERT INTO extLinks VALUES('Drone Collection',NULL);
INSERT INTO extLinks VALUES('Drone Assembly',NULL);
INSERT INTO extLinks VALUES('Drone Gathering',NULL);
INSERT INTO extLinks VALUES('Drone Surveillance',NULL);
INSERT INTO extLinks VALUES('Drone Menagerie',NULL);
INSERT INTO extLinks VALUES('Drone Herd',NULL);
INSERT INTO extLinks VALUES('Drone Squad',NULL);
INSERT INTO extLinks VALUES('Drone Patrol',NULL);
INSERT INTO extLinks VALUES('Drone Horde',NULL);
INSERT INTO extLinks VALUES('Angel Hideout',NULL);
INSERT INTO extLinks VALUES('Angel Lookout',NULL);
INSERT INTO extLinks VALUES('Angel Watch',NULL);
INSERT INTO extLinks VALUES('Angel Vigil',NULL);
INSERT INTO extLinks VALUES('Provisional Angel Outpost',NULL);
INSERT INTO extLinks VALUES('Angel Outpost',NULL);
INSERT INTO extLinks VALUES('Minor Angel Annex',NULL);
INSERT INTO extLinks VALUES('Angel Annex',NULL);
INSERT INTO extLinks VALUES('Angel Base',NULL);
INSERT INTO extLinks VALUES('Angel Fortress',NULL);
INSERT INTO extLinks VALUES('Angel Military Complex',NULL);
INSERT INTO extLinks VALUES('Angel Provincial HQ',NULL);
INSERT INTO extLinks VALUES('Angel Domination Fleet Staging Point',NULL);
INSERT INTO extLinks VALUES('Blood Hideout',NULL);
INSERT INTO extLinks VALUES('Blood Lookout',NULL);
INSERT INTO extLinks VALUES('Blood Watch',NULL);
INSERT INTO extLinks VALUES('Blood Vigil',NULL);
INSERT INTO extLinks VALUES('Provisional Blood Outpost',NULL);
INSERT INTO extLinks VALUES('Blood Raider Outpost',NULL);
INSERT INTO extLinks VALUES('Minor Blood Annex',NULL);
INSERT INTO extLinks VALUES('Blood Annex',NULL);
INSERT INTO extLinks VALUES('Blood Raider Base',NULL);
INSERT INTO extLinks VALUES('Blood Raider Fortress',NULL);
INSERT INTO extLinks VALUES('Blood Military Complex',NULL);
INSERT INTO extLinks VALUES('Blood Provincial HQ',NULL);
INSERT INTO extLinks VALUES('Dark Blood Fleet Staging Point',NULL);
INSERT INTO extLinks VALUES('Gurista Hideout',NULL);
INSERT INTO extLinks VALUES('Gurista Lookout',NULL);
INSERT INTO extLinks VALUES('Gurista Watch',NULL);
INSERT INTO extLinks VALUES('Gurista Vigil',NULL);
INSERT INTO extLinks VALUES('Provisional Gurista Outpost',NULL);
INSERT INTO extLinks VALUES('Gurista Outpost',NULL);
INSERT INTO extLinks VALUES('Minor Guristas Annex',NULL);
INSERT INTO extLinks VALUES('Guristas Annex',NULL);
INSERT INTO extLinks VALUES('Gurista Base',NULL);
INSERT INTO extLinks VALUES('Gurista Fortress',NULL);
INSERT INTO extLinks VALUES('Gurista Military Complex',NULL);
INSERT INTO extLinks VALUES('Gurista Provincial HQ',NULL);
INSERT INTO extLinks VALUES('Dread Guristas Fleet Staging Point',NULL);
INSERT INTO extLinks VALUES('Sansha Hideout',NULL);
INSERT INTO extLinks VALUES('Sansha Lookout',NULL);
INSERT INTO extLinks VALUES('Sansha Watch',NULL);
INSERT INTO extLinks VALUES('Sansha Vigil',NULL);
INSERT INTO extLinks VALUES('Provisional Sansha Outpost',NULL);
INSERT INTO extLinks VALUES('Sansha Outpost',NULL);
INSERT INTO extLinks VALUES('Minor Sansha Annex',NULL);
INSERT INTO extLinks VALUES('Sansha Annex',NULL);
INSERT INTO extLinks VALUES('Sansha Base',NULL);
INSERT INTO extLinks VALUES('Sansha Fortress',NULL);
INSERT INTO extLinks VALUES('Sansha Military Complex',NULL);
INSERT INTO extLinks VALUES('Sansha Provincial HQ',NULL);
INSERT INTO extLinks VALUES('True Sansha Fleet Staging Point',NULL);
INSERT INTO extLinks VALUES('Serpentis Hideout',NULL);
INSERT INTO extLinks VALUES('Serpentis Lookout',NULL);
INSERT INTO extLinks VALUES('Serpentis Watch',NULL);
INSERT INTO extLinks VALUES('Serpentis Vigil',NULL);
INSERT INTO extLinks VALUES('Provisional Serpentis Outpost',NULL);
INSERT INTO extLinks VALUES('Serpentis Outpost',NULL);
INSERT INTO extLinks VALUES('Minor Serpentis Annex',NULL);
INSERT INTO extLinks VALUES('Serpentis Annex',NULL);
INSERT INTO extLinks VALUES('Serpentis Base',NULL);
INSERT INTO extLinks VALUES('Serpentis Fortress',NULL);
INSERT INTO extLinks VALUES('Serpentis Military Complex',NULL);
INSERT INTO extLinks VALUES('Serpentis Provincial HQ',NULL);
INSERT INTO extLinks VALUES('Shadow Serpentis Fleet Staging Point',NULL);
INSERT INTO extLinks VALUES('Haunted Yard',NULL);
INSERT INTO extLinks VALUES('Desolate Site',NULL);
INSERT INTO extLinks VALUES('Chemical Yard',NULL);
INSERT INTO extLinks VALUES('Rogue Trial Yard',NULL);
INSERT INTO extLinks VALUES('Dirty Site',NULL);
INSERT INTO extLinks VALUES('Ruins',NULL);
INSERT INTO extLinks VALUES('Independence',NULL);
INSERT INTO extLinks VALUES('Radiance',NULL);
INSERT INTO extLinks VALUES('Hierarchy',NULL);
INSERT INTO extLinks VALUES('Minmatar Contracted Bio-Farm',NULL);
INSERT INTO extLinks VALUES('Angel Creo-Corp Mining',NULL);
INSERT INTO extLinks VALUES('Angel Repurposed Outpost',NULL);
INSERT INTO extLinks VALUES('Angel Cartel Occupied Mining Colony',NULL);
INSERT INTO extLinks VALUES('Angel''s Red Light District',NULL);
INSERT INTO extLinks VALUES('Angel Mineral Acquisition Outpost',NULL);
INSERT INTO extLinks VALUES('Angel Military Operations Complex',NULL);
INSERT INTO extLinks VALUES('Cartel Prisoner Retention',NULL);
INSERT INTO extLinks VALUES('Angel Cartel Naval Shipyard',NULL);
INSERT INTO extLinks VALUES('Old Meanie - Cultivation Center',NULL);
INSERT INTO extLinks VALUES('Blood Raider Human Farm',NULL);
INSERT INTO extLinks VALUES('Blood Raider Intelligence Collection Point',NULL);
INSERT INTO extLinks VALUES('Mul-Zatah Monastery',NULL);
INSERT INTO extLinks VALUES('Blood Raider Psychotropics Depot',NULL);
INSERT INTO extLinks VALUES('Crimson Hand Supply Depot',NULL);
INSERT INTO extLinks VALUES('Blood Raider Coordination Center',NULL);
INSERT INTO extLinks VALUES('Blood Raider Prison Camp',NULL);
INSERT INTO extLinks VALUES('Blood Raider Naval Shipyard',NULL);
INSERT INTO extLinks VALUES('Pith Robux Asteroid Mining & Co.',NULL);
INSERT INTO extLinks VALUES('Pith Merchant Depot',NULL);
INSERT INTO extLinks VALUES('Guristas Guerilla Grounds',NULL);
INSERT INTO extLinks VALUES('Guristas Scout Outpost',NULL);
INSERT INTO extLinks VALUES('Guristas Hallucinogen Supply Waypoint',NULL);
INSERT INTO extLinks VALUES('Guristas Troop Reinvigoration Camp',NULL);
INSERT INTO extLinks VALUES('Gurista Military Operations Complex',NULL);
INSERT INTO extLinks VALUES('Pith''s Penal Complex',NULL);
INSERT INTO extLinks VALUES('The Maze',NULL);
INSERT INTO extLinks VALUES('Sansha Military Outpost',NULL);
INSERT INTO extLinks VALUES('Sansha Acclimatization Facility',NULL);
INSERT INTO extLinks VALUES('Sansha''s Command Relay Outpost',NULL);
INSERT INTO extLinks VALUES('Sansha''s Nation Occupied Mining Colony',NULL);
INSERT INTO extLinks VALUES('Sansha''s Nation Neural Paralytic Facility',NULL);
INSERT INTO extLinks VALUES('Sansha War Supply Complex',NULL);
INSERT INTO extLinks VALUES('Sansha Military Operations Complex',NULL);
INSERT INTO extLinks VALUES('Sansha Prison Camp',NULL);
INSERT INTO extLinks VALUES('Centus Assembly T.P. Co.',NULL);
INSERT INTO extLinks VALUES('Serpentis Drug Outlet',NULL);
INSERT INTO extLinks VALUES('Serpentis Live Cargo Distribution Facilities',NULL);
INSERT INTO extLinks VALUES('Serpentis Narcotic Warehouses',NULL);
INSERT INTO extLinks VALUES('Serpentis Phi-Outpost',NULL);
INSERT INTO extLinks VALUES('Serpentis Corporation Hydroponics Site',NULL);
INSERT INTO extLinks VALUES('Serpentis Logistical Outpost',NULL);
INSERT INTO extLinks VALUES('Serpentis Paramilitary Complex',NULL);
INSERT INTO extLinks VALUES('Serpentis Prison Camp',NULL);
INSERT INTO extLinks VALUES('Serpentis Fleet Shipyard',NULL);
INSERT INTO extLinks VALUES('Rogue Drone Infestation Sprout',NULL);
INSERT INTO extLinks VALUES('Rogue Drone Asteroid Infestation',NULL);
INSERT INTO extLinks VALUES('Outgrowth Rogue Drone Hive',NULL);
INSERT INTO extLinks VALUES('Angel Chemical Lab',NULL);
INSERT INTO extLinks VALUES('Angel Gas Processing Site',NULL);
INSERT INTO extLinks VALUES('Elohim Sooth Sayer Distribution Base',NULL);
INSERT INTO extLinks VALUES('Elohim X-Instinct Distribution Base',NULL);
INSERT INTO extLinks VALUES('Elohim Sooth Sayer Production Facility',NULL);
INSERT INTO extLinks VALUES('Elohim X-Instinct Production Facility',NULL);
INSERT INTO extLinks VALUES('Digital Matrix',NULL);
INSERT INTO extLinks VALUES('Digital Network',NULL);
INSERT INTO extLinks VALUES('Blood Raider Chemical Lab',NULL);
INSERT INTO extLinks VALUES('Blood Raider Gas Processing Site',NULL);
INSERT INTO extLinks VALUES('CHAIN Mindflood Distribution Base',NULL);
INSERT INTO extLinks VALUES('CHAIN Mindflood Production Facility',NULL);
INSERT INTO extLinks VALUES('Digital Complex',NULL);
INSERT INTO extLinks VALUES('Guristas Chemical Lab',NULL);
INSERT INTO extLinks VALUES('Guristas Gas Processing Site',NULL);
INSERT INTO extLinks VALUES('H-PA Crew Blue Pill Distribution Base',NULL);
INSERT INTO extLinks VALUES('H-PA Crew Crash Distribution Base',NULL);
INSERT INTO extLinks VALUES('H-PA Crew Blue Pill Production Facility',NULL);
INSERT INTO extLinks VALUES('H-PA Crew Crash Production Facility',NULL);
INSERT INTO extLinks VALUES('Digital Plexus',NULL);
INSERT INTO extLinks VALUES('Digital Convolution',NULL);
INSERT INTO extLinks VALUES('Sansha Chemical Lab',NULL);
INSERT INTO extLinks VALUES('Sansha Gas Processing Site',NULL);
INSERT INTO extLinks VALUES('PDW-09FX Frentix Distribution Base',NULL);
INSERT INTO extLinks VALUES('PDW-09FX Frentix Production Facility',NULL);
INSERT INTO extLinks VALUES('Digital Circuitry',NULL);
INSERT INTO extLinks VALUES('Serpentis Chemical Lab',NULL);
INSERT INTO extLinks VALUES('Serpentis Gas Processing Site',NULL);
INSERT INTO extLinks VALUES('Core Runner Drop Distribution',NULL);
INSERT INTO extLinks VALUES('Core Runner Exile Distribution Base',NULL);
INSERT INTO extLinks VALUES('Core Runner Drop Production Facility',NULL);
INSERT INTO extLinks VALUES('Core Runner Exile Production Facility',NULL);
INSERT INTO extLinks VALUES('Digital Compound',NULL);
INSERT INTO extLinks VALUES('Digital Tessellation',NULL);
