INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Blood Raider', 'EM/Thermal', 'EM');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Guristas', 'Kinetic/Thermal', 'Kinetic');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Sanshas', 'EM/Thermal', 'EM');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Serpentis', 'Thermal/Kinetic', 'Kinetic');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Angel', 'Explosive/Kinetic', 'Explosive');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Mordus', 'Kinetic/Thermal', 'Kinetic');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Rogue Drones', 'Explosive/Kinetic', 'EM');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Mercenary', 'EM/Thermal', 'Thermal');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Minmatar', 'Thermal', ' Explo');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Gallente', 'Kinetic/Thermal', 'Thermal');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Amarr', 'EM/Thermal', 'Thermal');
INSERT INTO ratsDamage (race, damageToGet, damageToUse) VALUES ('Caldari', 'Kinetic/Thermal', 'Kinetic');