INSERT INTO regionRats(regionName,rats) VALUES ('Aridia','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Black Rise','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('The Bleak Lands','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('The Citadel','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Derelik','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Devoid','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Domain','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Essence','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Everyshore','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('The Forge','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Genesis','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Heimatar','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Kador','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Khanid','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Kor-Azor','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Lonetrek','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Metropolis','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Molden Heath','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Placid','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Sinq Laison','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Solitude','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Tash-Murkon','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Verge Vendor','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Branch','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Cache','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Catch','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Cloud Ring','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Cobalt Edge','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Curse','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Deklein','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Delve','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Detorid','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Esoteria','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Etherium Reach','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Fade','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Feythabolis','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Fountain','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Geminate','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Great Wildlands','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Immensea','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Impass','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Insmother','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('The Kalevala Expanse','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Malpais','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Oasa','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Omist','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Outer Passage','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Outer Ring','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Paragon Soul','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Period Basis','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Perrigen Falls','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Pochven',NULL);
INSERT INTO regionRats(regionName,rats) VALUES ('Providence','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Pure Blind','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Querious','Blood Raiders');
INSERT INTO regionRats(regionName,rats) VALUES ('Scalding Pass','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('The Spire','Drones');
INSERT INTO regionRats(regionName,rats) VALUES ('Stain','Sanshas');
INSERT INTO regionRats(regionName,rats) VALUES ('Syndicate','Serpentis');
INSERT INTO regionRats(regionName,rats) VALUES ('Tenal','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Tenerifis','Angels');
INSERT INTO regionRats(regionName,rats) VALUES ('Tribute','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Vale of the Silent','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Venal','Guristas');
INSERT INTO regionRats(regionName,rats) VALUES ('Wicked Creek','Angels');
