version: "3.7"
name: evemapper

services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ../
      dockerfile: install/Dockerfile
    image: evemapper
    container_name: evemapper-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - evemapper

  nginx:
    image: nginx:alpine
    container_name: evemapper-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - evemapper

networks:
  evemapper:
    driver: bridge
